name: Singularity Build
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  # Do the builds on all pull requests (to test them), but don't deploy on PR (see below)
  pull_request: []
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    env: 
      username: myoung3
      organization: kaufman-lab
    strategy:
      fail-fast: false
      matrix:
        arrays: [ 
          {repository: "tensorflow_buildenvironment", tag: "v1", definitionfile: "tensorflow_buildenvironmentv1.def"}
        ]
    steps:
    - name: git checkout
      uses: actions/checkout@v1
      
    - name: Get changed definition files
      id: changed-files-def
      uses: tj-actions/changed-files@v9.1
      with:
        files: |
          .(def)$
    - name: Print changed definition files
      run: echo ${{ steps.changed-files-def.outputs.all_modified_files }}
            
    - name: Set up Go
      if: contains(steps.changed-files-def.outputs.all_modified_files, matrix.arrays.definitionfile) || github.event_name == 'workflow_dispatch'
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Dependencies
      if: contains(steps.changed-files-def.outputs.all_modified_files, matrix.arrays.definitionfile) || github.event_name == 'workflow_dispatch'
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config
          
    - name: Install Singularity
      if: contains(steps.changed-files-def.outputs.all_modified_files, matrix.arrays.definitionfile) || github.event_name == 'workflow_dispatch'
      env:
        SINGULARITY_VERSION: 3.8.1
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
        tar xzv && \
        cd singularity-ce-${SINGULARITY_VERSION} && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install          
          
    - name: Build container
      if: contains(steps.changed-files-def.outputs.all_modified_files, matrix.arrays.definitionfile) || github.event_name == 'workflow_dispatch'
      run: |
       ls 
       
       if [ -f "${{ matrix.arrays.definitionfile }}" ]; then
         sudo -E singularity build output.sif ${{ matrix.arrays.definitionfile }}
       else
         echo "${SINGULARITY_RECIPE} is not found."
         echo "Present working directory: $PWD"
       fi
    - name: log in to github container registry and deploy
      if: (github.event_name != 'pull_request') && (contains(steps.changed-files-def.outputs.all_modified_files, matrix.arrays.definitionfile) || github.event_name == 'workflow_dispatch')
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ env.username }} --password-stdin oras://ghcr.io
        singularity remote list
        singularity push output.sif oras://ghcr.io/${{ env.organization }}/${{ matrix.arrays.repository }}:${{ matrix.arrays.tag}} 
       
