# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, test2]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tensorflow-version: [2.5]
        march: [skylake, skylake-avx512]
        mtune: [skylake, skylake-avx512, cascadelake, causeanerror]
    # Steps represent a sequence of tasks that will be executed as part of the job
   
    steps:
    - name: test
      run: echo "bleh" >> /tmp/tensorflow.whl

    - uses: actions/upload-artifact@v2
      with:
        name: tf${{ tensorflow-version }}march_${{ matrix.march }}_mtune${{ mtune }}
        path: /tmp/tensorflow.whl

  release:
    runs-on: ubuntu-latest
    needs: build #this depends on successful completion of *all* matrix jobs.
    steps:
    - name: hellow world
      run: echo "hello world"
 

    - name: checkout
      uses: actions/checkout@v2
    - run: mkdir /tmp/artifcats
    - name: download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: /tmp/artifcats
    - run: ls
    
